version: '3.8'

services:
    server:
        container_name: nginx_server
        build:
            context: .
            dockerfile: dockerfiles/nginx.dockerfile
        ports:
            - '8000:80'
        volumes:
            - ./src:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - php
            - mysql
            - adminer
        networks:
            - twitter_network

    php:
        container_name: php_server
        ports:
            - '6001:6001'
        build:
            context: .
            dockerfile: dockerfiles/php.dockerfile
        volumes:
            - ./src:/var/www/html:delegated
        networks:
            - twitter_network

    mysql:
        container_name: mysql_server
        image: mysql:5.7
        env_file:
            - ./env/mysql.env
        networks:
            - twitter_network

    adminer:
        container_name: adminer
        image: adminer
        restart: always
        ports:
            - 8080:8080
        networks:
            - twitter_network

    composer:
        build:
            context: ./dockerfiles
            dockerfile: composer.dockerfile
        volumes:
            - ./src:/var/www/html
        networks:
            - twitter_network

    npm:
        image: node:14
        working_dir: /var/www/html
        entrypoint: ["npm"]
        volumes:
           - ./src:/var/www/html
        networks:
            - twitter_network

networks:
  twitter_network:
    driver: bridge
